name: Publish package to GitHub Packages  

on: push  

jobs:  
  publish:  
    runs-on: ubuntu-latest  
    permissions:   
      contents: read  
      packages: write  
    
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v3  
      
      - name: Setup Java  
        uses: actions/setup-java@v3  
        with:  
          java-version: '21'  
          distribution: 'adopt'  
      
      - name: Publish package  
        run: mvn clean --batch-mode deploy  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}